require:
  - rubocop-rails

# Looks for uses of `default_scope`.
Rails/DefaultScope:
  Enabled: true

# Looks for direct access to environment variables through the `ENV` variable
# within the application code.
Rails/EnvironmentVariableAccess:
  Enabled: true
  AllowReads: true

# Checks for places where ordering by `id` column is used.
Rails/OrderById:
  Enabled: true

# Enforces the use of `ids` over `pluck(:id)` and `pluck(primary_key)`.
Rails/PluckId:
  Enabled: true

# Checks for the usage of `require_dependency`.
Rails/RequireDependency:
  Enabled: true

# Checks whether the migration implements either a `change` method or both an
# `up` and a `down` method.
Rails/ReversibleMigrationMethodDefinition:
  Enabled: true

# Identifies possible cases where Active Record `save!` or related should be
# used instead of `save` because the model might have failed to save and an
# exception is better than unhandled failure.
Rails/SaveBang:
  Enabled: true
  AllowImplicitReturn: false

# Enforces the use of the comment option when adding a new table or column to
# the database during a migration.
Rails/SchemaComment:
  Enabled: true

# Enforces the absence of explicit table name assignment.
Rails/TableNameAssignment:
  Enabled: true
