inherit_from:
  - https://raw.githubusercontent.com/jgarber623/rubocop-configs/main/.rubocop.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

# Identifies places where inefficient `readlines` method can be replaced by
# `each_line` to avoid fully loading file content into memory.
Performance/IoReadlines:
  Enabled: true

# Identifies places where select.map can be replaced by filter_map.
# Requires Ruby 2.7
Performance/SelectMap:
  Enabled: true

# Looks for uses of `default_scope`.
Rails/DefaultScope:
  Enabled: true

# Checks for places where ordering by `id` column is used.
Rails/OrderById:
  Enabled: true

# Enforces the use of `ids` over `pluck(:id)` and `pluck(primary_key)`.
Rails/PluckId:
  Enabled: true

# Checks whether the migration implements either a `change` method or both an
# `up` and a `down` method.
Rails/ReversibleMigrationMethodDefinition:
  Enabled: true

# Identifies possible cases where Active Record `save!` or related should be
# used instead of `save` because the model might have failed to save and an
# exception is better than unhandled failure.
Rails/SaveBang:
  Enabled: true

# Enforces the use of the comment option when adding a new table or column to
# the database during a migration.
Rails/SchemaComment:
  Enabled: true

# Avoid opening modules and defining specs within them.
RSpec/DescribedClassModuleWrapping:
  Enabled: true
